package com.zdb.demo.entity;

import java.io.Serializable;

/**
 * 广告中心
 * Advertisement
 * 数据库表：advertisement
 */
public class Advertisement implements Serializable {

    /**
     * 主键
     * 表字段 : advertisement.advertisement_id
     */
    private Integer advertisementId;

    /**
     * 商家id
     * 表字段 : advertisement.store_id
     */
    private Integer storeId;

    /**
     * 广告类型 0-进入广告 2-顶部轮播
     * 表字段 : advertisement.advertisement_type
     */
    private Integer advertisementType;

    /**
     * 图片路径
     * 表字段 : advertisement.advertisement_img
     */
    private String advertisementImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table advertisement
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键 字段:advertisement.advertisement_id
     *
     * @return advertisement.advertisement_id, 主键
     */
    public Integer getAdvertisementId() {
        return advertisementId;
    }

    /**
     * 设置 主键 字段:advertisement.advertisement_id
     *
     * @param advertisementId the value for advertisement.advertisement_id, 主键
     */
    public void setAdvertisementId(Integer advertisementId) {
        this.advertisementId = advertisementId;
    }

    /**
     * 获取 商家id 字段:advertisement.store_id
     *
     * @return advertisement.store_id, 商家id
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * 设置 商家id 字段:advertisement.store_id
     *
     * @param storeId the value for advertisement.store_id, 商家id
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * 获取 广告类型 0-进入广告 2-顶部轮播 字段:advertisement.advertisement_type
     *
     * @return advertisement.advertisement_type, 广告类型 0-进入广告 2-顶部轮播
     */
    public Integer getAdvertisementType() {
        return advertisementType;
    }

    /**
     * 设置 广告类型 0-进入广告 2-顶部轮播 字段:advertisement.advertisement_type
     *
     * @param advertisementType the value for advertisement.advertisement_type, 广告类型 0-进入广告 2-顶部轮播
     */
    public void setAdvertisementType(Integer advertisementType) {
        this.advertisementType = advertisementType;
    }

    /**
     * 获取 图片路径 字段:advertisement.advertisement_img
     *
     * @return advertisement.advertisement_img, 图片路径
     */
    public String getAdvertisementImg() {
        return advertisementImg;
    }

    /**
     * 设置 图片路径 字段:advertisement.advertisement_img
     *
     * @param advertisementImg the value for advertisement.advertisement_img, 图片路径
     */
    public void setAdvertisementImg(String advertisementImg) {
        this.advertisementImg = advertisementImg == null ? null : advertisementImg.trim();
    }
}