package com.zdb.demo.entity;

import java.util.ArrayList;
import java.util.List;

public class MenuTypeExample {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu_type
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu_type
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu_type
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu_type
     *
     * @mbggenerated
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu_type
     *
     * @mbggenerated
     */
    protected Integer limitEnd;

    /**
     *  构造查询条件,menu_type
     */
    public MenuTypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *  设置排序字段,menu_type
     *
     * @param orderByClause 排序字段
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *  获取排序字段,menu_type
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *  设置过滤重复数据,menu_type
     *
     * @param distinct 是否过滤重复数据
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *  是否过滤重复数据,menu_type
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *  获取当前的查询条件实例,menu_type
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * ,menu_type
     *
     * @param criteria 过滤条件实例
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * ,menu_type
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *  创建一个查询条件,menu_type
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *  内部构建查询条件对象,menu_type
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *  清除查询条件,menu_type
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * ,menu_type
     *
     * @param limitStart
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * ,menu_type
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * ,menu_type
     *
     * @param limitEnd
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * ,menu_type
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * 菜品类型表
     * GeneratedCriteria
     * 数据库表：menu_type
     */
    protected abstract static class GeneratedCriteria {

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMenuTypeIdIsNull() {
            addCriterion("menu_type_id is null");
            return (Criteria) this;
        }

        public Criteria andMenuTypeIdIsNotNull() {
            addCriterion("menu_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andMenuTypeIdEqualTo(Integer value) {
            addCriterion("menu_type_id =", value, "menuTypeId");
            return (Criteria) this;
        }

        public Criteria andMenuTypeIdNotEqualTo(Integer value) {
            addCriterion("menu_type_id <>", value, "menuTypeId");
            return (Criteria) this;
        }

        public Criteria andMenuTypeIdGreaterThan(Integer value) {
            addCriterion("menu_type_id >", value, "menuTypeId");
            return (Criteria) this;
        }

        public Criteria andMenuTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("menu_type_id >=", value, "menuTypeId");
            return (Criteria) this;
        }

        public Criteria andMenuTypeIdLessThan(Integer value) {
            addCriterion("menu_type_id <", value, "menuTypeId");
            return (Criteria) this;
        }

        public Criteria andMenuTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("menu_type_id <=", value, "menuTypeId");
            return (Criteria) this;
        }

        public Criteria andMenuTypeIdIn(List<Integer> values) {
            addCriterion("menu_type_id in", values, "menuTypeId");
            return (Criteria) this;
        }

        public Criteria andMenuTypeIdNotIn(List<Integer> values) {
            addCriterion("menu_type_id not in", values, "menuTypeId");
            return (Criteria) this;
        }

        public Criteria andMenuTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("menu_type_id between", value1, value2, "menuTypeId");
            return (Criteria) this;
        }

        public Criteria andMenuTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("menu_type_id not between", value1, value2, "menuTypeId");
            return (Criteria) this;
        }

        public Criteria andMenuTypeNameIsNull() {
            addCriterion("menu_type_name is null");
            return (Criteria) this;
        }

        public Criteria andMenuTypeNameIsNotNull() {
            addCriterion("menu_type_name is not null");
            return (Criteria) this;
        }

        public Criteria andMenuTypeNameEqualTo(String value) {
            addCriterion("menu_type_name =", value, "menuTypeName");
            return (Criteria) this;
        }

        public Criteria andMenuTypeNameNotEqualTo(String value) {
            addCriterion("menu_type_name <>", value, "menuTypeName");
            return (Criteria) this;
        }

        public Criteria andMenuTypeNameGreaterThan(String value) {
            addCriterion("menu_type_name >", value, "menuTypeName");
            return (Criteria) this;
        }

        public Criteria andMenuTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("menu_type_name >=", value, "menuTypeName");
            return (Criteria) this;
        }

        public Criteria andMenuTypeNameLessThan(String value) {
            addCriterion("menu_type_name <", value, "menuTypeName");
            return (Criteria) this;
        }

        public Criteria andMenuTypeNameLessThanOrEqualTo(String value) {
            addCriterion("menu_type_name <=", value, "menuTypeName");
            return (Criteria) this;
        }

        public Criteria andMenuTypeNameLike(String value) {
            addCriterion("menu_type_name like", value, "menuTypeName");
            return (Criteria) this;
        }

        public Criteria andMenuTypeNameNotLike(String value) {
            addCriterion("menu_type_name not like", value, "menuTypeName");
            return (Criteria) this;
        }

        public Criteria andMenuTypeNameIn(List<String> values) {
            addCriterion("menu_type_name in", values, "menuTypeName");
            return (Criteria) this;
        }

        public Criteria andMenuTypeNameNotIn(List<String> values) {
            addCriterion("menu_type_name not in", values, "menuTypeName");
            return (Criteria) this;
        }

        public Criteria andMenuTypeNameBetween(String value1, String value2) {
            addCriterion("menu_type_name between", value1, value2, "menuTypeName");
            return (Criteria) this;
        }

        public Criteria andMenuTypeNameNotBetween(String value1, String value2) {
            addCriterion("menu_type_name not between", value1, value2, "menuTypeName");
            return (Criteria) this;
        }

        public Criteria andMenuTypeWeightIsNull() {
            addCriterion("menu_type_weight is null");
            return (Criteria) this;
        }

        public Criteria andMenuTypeWeightIsNotNull() {
            addCriterion("menu_type_weight is not null");
            return (Criteria) this;
        }

        public Criteria andMenuTypeWeightEqualTo(Integer value) {
            addCriterion("menu_type_weight =", value, "menuTypeWeight");
            return (Criteria) this;
        }

        public Criteria andMenuTypeWeightNotEqualTo(Integer value) {
            addCriterion("menu_type_weight <>", value, "menuTypeWeight");
            return (Criteria) this;
        }

        public Criteria andMenuTypeWeightGreaterThan(Integer value) {
            addCriterion("menu_type_weight >", value, "menuTypeWeight");
            return (Criteria) this;
        }

        public Criteria andMenuTypeWeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("menu_type_weight >=", value, "menuTypeWeight");
            return (Criteria) this;
        }

        public Criteria andMenuTypeWeightLessThan(Integer value) {
            addCriterion("menu_type_weight <", value, "menuTypeWeight");
            return (Criteria) this;
        }

        public Criteria andMenuTypeWeightLessThanOrEqualTo(Integer value) {
            addCriterion("menu_type_weight <=", value, "menuTypeWeight");
            return (Criteria) this;
        }

        public Criteria andMenuTypeWeightIn(List<Integer> values) {
            addCriterion("menu_type_weight in", values, "menuTypeWeight");
            return (Criteria) this;
        }

        public Criteria andMenuTypeWeightNotIn(List<Integer> values) {
            addCriterion("menu_type_weight not in", values, "menuTypeWeight");
            return (Criteria) this;
        }

        public Criteria andMenuTypeWeightBetween(Integer value1, Integer value2) {
            addCriterion("menu_type_weight between", value1, value2, "menuTypeWeight");
            return (Criteria) this;
        }

        public Criteria andMenuTypeWeightNotBetween(Integer value1, Integer value2) {
            addCriterion("menu_type_weight not between", value1, value2, "menuTypeWeight");
            return (Criteria) this;
        }
    }

    /**
     * 类注释
     * Criteria
     * 数据库表：menu_type
     */
    public static class Criteria extends GeneratedCriteria {


        protected Criteria() {
            super();
        }
    }

    /**
     * 菜品类型表
     * Criterion
     * 数据库表：menu_type
     */
    public static class Criterion {

        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}