package com.zdb.demo.entity;

import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Objects;

/**
 * 菜品信息
 * Menu
 * 数据库表：menu
 */
@Data
public class Menu implements Serializable {

    /**
     * 菜品id
     * 表字段 : menu.menu_id
     */
    private Integer menuId;

    /**
     * 商家关联id
     * 表字段 : menu.menu_store_id
     */
    private Integer menuStoreId;
    /**
     * 商家名称
     */
    private String storeName;

    /**
     * 菜品名称
     * 表字段 : menu.menu_name
     */
    private String menuName;

    /**
     * 菜品价格
     * 表字段 : menu.menu_price
     */
    private BigDecimal menuPrice;

    /**
     * 菜品折扣
     * 表字段 : menu.menu_discount
     */
    private BigDecimal menuDiscount;

    /**
     * 菜品销量
     * 表字段 : menu.menu_sales
     */
    private Long menuSales;

    /**
     * 菜品图片
     * 表字段 : menu.menu_img
     */
    private String menuImg;

    /**
     * 菜品类型
     * 表字段 : menu.menu_type
     */
    private Integer menuType;

    /**
     * 菜品口味 1不辣/2微辣/3中辣/特辣
     * 表字段 : menu.menu_flavor
     */
    private Integer menuFlavor;

    /**
     * 好评量
     * 表字段 : menu.menu_star
     */
    private Integer menuStar;

    /**
     * 好评百分比
     * 表字段 : menu.menu_star_pecent
     */
    private BigDecimal menuStarPecent;

    /**
     * 删除 0未删除/1已删除
     * 表字段 : menu.menu_del
     */
    private Integer menuDel;

    /**
     * 招牌 0非招牌/1招牌
     * 表字段 : menu.menu_is_nice
     */
    private Integer menuIsNice;
    /**
     * 折后价格
     */
    private BigDecimal priceAfterDiscount;
    /**
     * 类型名称
     */
    private String menuTypeDes;

    /**
     * 菜品数量
     */
    private Integer menuNum;

    /**
     * 是否收藏
     */
    private Boolean isCollect;

    /**
     * 根据哪个菜品推荐
     */
    private String recommendByMenu;

    /**
     * 菜品描述
     * 表字段 : menu.menu_text
     */
    private String menuText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

}