package com.zdb.demo.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class MenuExample {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu
     *
     * @mbggenerated
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu
     *
     * @mbggenerated
     */
    protected Integer limitEnd;

    /**
     *  构造查询条件,menu
     */
    public MenuExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *  设置排序字段,menu
     *
     * @param orderByClause 排序字段
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *  获取排序字段,menu
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *  设置过滤重复数据,menu
     *
     * @param distinct 是否过滤重复数据
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *  是否过滤重复数据,menu
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *  获取当前的查询条件实例,menu
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * ,menu
     *
     * @param criteria 过滤条件实例
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * ,menu
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *  创建一个查询条件,menu
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *  内部构建查询条件对象,menu
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *  清除查询条件,menu
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * ,menu
     *
     * @param limitStart
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * ,menu
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * ,menu
     *
     * @param limitEnd
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * ,menu
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * 菜品信息
     * GeneratedCriteria
     * 数据库表：menu
     */
    protected abstract static class GeneratedCriteria {

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMenuIdIsNull() {
            addCriterion("menu_id is null");
            return (Criteria) this;
        }

        public Criteria andMenuIdIsNotNull() {
            addCriterion("menu_id is not null");
            return (Criteria) this;
        }

        public Criteria andMenuIdEqualTo(Integer value) {
            addCriterion("menu_id =", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotEqualTo(Integer value) {
            addCriterion("menu_id <>", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdGreaterThan(Integer value) {
            addCriterion("menu_id >", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("menu_id >=", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdLessThan(Integer value) {
            addCriterion("menu_id <", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdLessThanOrEqualTo(Integer value) {
            addCriterion("menu_id <=", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdIn(List<Integer> values) {
            addCriterion("menu_id in", values, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotIn(List<Integer> values) {
            addCriterion("menu_id not in", values, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdBetween(Integer value1, Integer value2) {
            addCriterion("menu_id between", value1, value2, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotBetween(Integer value1, Integer value2) {
            addCriterion("menu_id not between", value1, value2, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuStoreIdIsNull() {
            addCriterion("menu_store_id is null");
            return (Criteria) this;
        }

        public Criteria andMenuStoreIdIsNotNull() {
            addCriterion("menu_store_id is not null");
            return (Criteria) this;
        }

        public Criteria andMenuStoreIdEqualTo(Integer value) {
            addCriterion("menu_store_id =", value, "menuStoreId");
            return (Criteria) this;
        }

        public Criteria andMenuStoreIdNotEqualTo(Integer value) {
            addCriterion("menu_store_id <>", value, "menuStoreId");
            return (Criteria) this;
        }

        public Criteria andMenuStoreIdGreaterThan(Integer value) {
            addCriterion("menu_store_id >", value, "menuStoreId");
            return (Criteria) this;
        }

        public Criteria andMenuStoreIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("menu_store_id >=", value, "menuStoreId");
            return (Criteria) this;
        }

        public Criteria andMenuStoreIdLessThan(Integer value) {
            addCriterion("menu_store_id <", value, "menuStoreId");
            return (Criteria) this;
        }

        public Criteria andMenuStoreIdLessThanOrEqualTo(Integer value) {
            addCriterion("menu_store_id <=", value, "menuStoreId");
            return (Criteria) this;
        }

        public Criteria andMenuStoreIdIn(List<Integer> values) {
            addCriterion("menu_store_id in", values, "menuStoreId");
            return (Criteria) this;
        }

        public Criteria andMenuStoreIdNotIn(List<Integer> values) {
            addCriterion("menu_store_id not in", values, "menuStoreId");
            return (Criteria) this;
        }

        public Criteria andMenuStoreIdBetween(Integer value1, Integer value2) {
            addCriterion("menu_store_id between", value1, value2, "menuStoreId");
            return (Criteria) this;
        }

        public Criteria andMenuStoreIdNotBetween(Integer value1, Integer value2) {
            addCriterion("menu_store_id not between", value1, value2, "menuStoreId");
            return (Criteria) this;
        }

        public Criteria andMenuNameIsNull() {
            addCriterion("menu_name is null");
            return (Criteria) this;
        }

        public Criteria andMenuNameIsNotNull() {
            addCriterion("menu_name is not null");
            return (Criteria) this;
        }

        public Criteria andMenuNameEqualTo(String value) {
            addCriterion("menu_name =", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotEqualTo(String value) {
            addCriterion("menu_name <>", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameGreaterThan(String value) {
            addCriterion("menu_name >", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameGreaterThanOrEqualTo(String value) {
            addCriterion("menu_name >=", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameLessThan(String value) {
            addCriterion("menu_name <", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameLessThanOrEqualTo(String value) {
            addCriterion("menu_name <=", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameLike(String value) {
            addCriterion("menu_name like", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotLike(String value) {
            addCriterion("menu_name not like", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameIn(List<String> values) {
            addCriterion("menu_name in", values, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotIn(List<String> values) {
            addCriterion("menu_name not in", values, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameBetween(String value1, String value2) {
            addCriterion("menu_name between", value1, value2, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotBetween(String value1, String value2) {
            addCriterion("menu_name not between", value1, value2, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuPriceIsNull() {
            addCriterion("menu_price is null");
            return (Criteria) this;
        }

        public Criteria andMenuPriceIsNotNull() {
            addCriterion("menu_price is not null");
            return (Criteria) this;
        }

        public Criteria andMenuPriceEqualTo(BigDecimal value) {
            addCriterion("menu_price =", value, "menuPrice");
            return (Criteria) this;
        }

        public Criteria andMenuPriceNotEqualTo(BigDecimal value) {
            addCriterion("menu_price <>", value, "menuPrice");
            return (Criteria) this;
        }

        public Criteria andMenuPriceGreaterThan(BigDecimal value) {
            addCriterion("menu_price >", value, "menuPrice");
            return (Criteria) this;
        }

        public Criteria andMenuPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("menu_price >=", value, "menuPrice");
            return (Criteria) this;
        }

        public Criteria andMenuPriceLessThan(BigDecimal value) {
            addCriterion("menu_price <", value, "menuPrice");
            return (Criteria) this;
        }

        public Criteria andMenuPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("menu_price <=", value, "menuPrice");
            return (Criteria) this;
        }

        public Criteria andMenuPriceIn(List<BigDecimal> values) {
            addCriterion("menu_price in", values, "menuPrice");
            return (Criteria) this;
        }

        public Criteria andMenuPriceNotIn(List<BigDecimal> values) {
            addCriterion("menu_price not in", values, "menuPrice");
            return (Criteria) this;
        }

        public Criteria andMenuPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("menu_price between", value1, value2, "menuPrice");
            return (Criteria) this;
        }

        public Criteria andMenuPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("menu_price not between", value1, value2, "menuPrice");
            return (Criteria) this;
        }

        public Criteria andMenuDiscountIsNull() {
            addCriterion("menu_discount is null");
            return (Criteria) this;
        }

        public Criteria andMenuDiscountIsNotNull() {
            addCriterion("menu_discount is not null");
            return (Criteria) this;
        }

        public Criteria andMenuDiscountEqualTo(BigDecimal value) {
            addCriterion("menu_discount =", value, "menuDiscount");
            return (Criteria) this;
        }

        public Criteria andMenuDiscountNotEqualTo(BigDecimal value) {
            addCriterion("menu_discount <>", value, "menuDiscount");
            return (Criteria) this;
        }

        public Criteria andMenuDiscountGreaterThan(BigDecimal value) {
            addCriterion("menu_discount >", value, "menuDiscount");
            return (Criteria) this;
        }

        public Criteria andMenuDiscountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("menu_discount >=", value, "menuDiscount");
            return (Criteria) this;
        }

        public Criteria andMenuDiscountLessThan(BigDecimal value) {
            addCriterion("menu_discount <", value, "menuDiscount");
            return (Criteria) this;
        }

        public Criteria andMenuDiscountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("menu_discount <=", value, "menuDiscount");
            return (Criteria) this;
        }

        public Criteria andMenuDiscountIn(List<BigDecimal> values) {
            addCriterion("menu_discount in", values, "menuDiscount");
            return (Criteria) this;
        }

        public Criteria andMenuDiscountNotIn(List<BigDecimal> values) {
            addCriterion("menu_discount not in", values, "menuDiscount");
            return (Criteria) this;
        }

        public Criteria andMenuDiscountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("menu_discount between", value1, value2, "menuDiscount");
            return (Criteria) this;
        }

        public Criteria andMenuDiscountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("menu_discount not between", value1, value2, "menuDiscount");
            return (Criteria) this;
        }

        public Criteria andMenuSalesIsNull() {
            addCriterion("menu_sales is null");
            return (Criteria) this;
        }

        public Criteria andMenuSalesIsNotNull() {
            addCriterion("menu_sales is not null");
            return (Criteria) this;
        }

        public Criteria andMenuSalesEqualTo(Long value) {
            addCriterion("menu_sales =", value, "menuSales");
            return (Criteria) this;
        }

        public Criteria andMenuSalesNotEqualTo(Long value) {
            addCriterion("menu_sales <>", value, "menuSales");
            return (Criteria) this;
        }

        public Criteria andMenuSalesGreaterThan(Long value) {
            addCriterion("menu_sales >", value, "menuSales");
            return (Criteria) this;
        }

        public Criteria andMenuSalesGreaterThanOrEqualTo(Long value) {
            addCriterion("menu_sales >=", value, "menuSales");
            return (Criteria) this;
        }

        public Criteria andMenuSalesLessThan(Long value) {
            addCriterion("menu_sales <", value, "menuSales");
            return (Criteria) this;
        }

        public Criteria andMenuSalesLessThanOrEqualTo(Long value) {
            addCriterion("menu_sales <=", value, "menuSales");
            return (Criteria) this;
        }

        public Criteria andMenuSalesIn(List<Long> values) {
            addCriterion("menu_sales in", values, "menuSales");
            return (Criteria) this;
        }

        public Criteria andMenuSalesNotIn(List<Long> values) {
            addCriterion("menu_sales not in", values, "menuSales");
            return (Criteria) this;
        }

        public Criteria andMenuSalesBetween(Long value1, Long value2) {
            addCriterion("menu_sales between", value1, value2, "menuSales");
            return (Criteria) this;
        }

        public Criteria andMenuSalesNotBetween(Long value1, Long value2) {
            addCriterion("menu_sales not between", value1, value2, "menuSales");
            return (Criteria) this;
        }

        public Criteria andMenuImgIsNull() {
            addCriterion("menu_img is null");
            return (Criteria) this;
        }

        public Criteria andMenuImgIsNotNull() {
            addCriterion("menu_img is not null");
            return (Criteria) this;
        }

        public Criteria andMenuImgEqualTo(String value) {
            addCriterion("menu_img =", value, "menuImg");
            return (Criteria) this;
        }

        public Criteria andMenuImgNotEqualTo(String value) {
            addCriterion("menu_img <>", value, "menuImg");
            return (Criteria) this;
        }

        public Criteria andMenuImgGreaterThan(String value) {
            addCriterion("menu_img >", value, "menuImg");
            return (Criteria) this;
        }

        public Criteria andMenuImgGreaterThanOrEqualTo(String value) {
            addCriterion("menu_img >=", value, "menuImg");
            return (Criteria) this;
        }

        public Criteria andMenuImgLessThan(String value) {
            addCriterion("menu_img <", value, "menuImg");
            return (Criteria) this;
        }

        public Criteria andMenuImgLessThanOrEqualTo(String value) {
            addCriterion("menu_img <=", value, "menuImg");
            return (Criteria) this;
        }

        public Criteria andMenuImgLike(String value) {
            addCriterion("menu_img like", value, "menuImg");
            return (Criteria) this;
        }

        public Criteria andMenuImgNotLike(String value) {
            addCriterion("menu_img not like", value, "menuImg");
            return (Criteria) this;
        }

        public Criteria andMenuImgIn(List<String> values) {
            addCriterion("menu_img in", values, "menuImg");
            return (Criteria) this;
        }

        public Criteria andMenuImgNotIn(List<String> values) {
            addCriterion("menu_img not in", values, "menuImg");
            return (Criteria) this;
        }

        public Criteria andMenuImgBetween(String value1, String value2) {
            addCriterion("menu_img between", value1, value2, "menuImg");
            return (Criteria) this;
        }

        public Criteria andMenuImgNotBetween(String value1, String value2) {
            addCriterion("menu_img not between", value1, value2, "menuImg");
            return (Criteria) this;
        }

        public Criteria andMenuTypeIsNull() {
            addCriterion("menu_type is null");
            return (Criteria) this;
        }

        public Criteria andMenuTypeIsNotNull() {
            addCriterion("menu_type is not null");
            return (Criteria) this;
        }

        public Criteria andMenuTypeEqualTo(Integer value) {
            addCriterion("menu_type =", value, "menuType");
            return (Criteria) this;
        }

        public Criteria andMenuTypeNotEqualTo(Integer value) {
            addCriterion("menu_type <>", value, "menuType");
            return (Criteria) this;
        }

        public Criteria andMenuTypeGreaterThan(Integer value) {
            addCriterion("menu_type >", value, "menuType");
            return (Criteria) this;
        }

        public Criteria andMenuTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("menu_type >=", value, "menuType");
            return (Criteria) this;
        }

        public Criteria andMenuTypeLessThan(Integer value) {
            addCriterion("menu_type <", value, "menuType");
            return (Criteria) this;
        }

        public Criteria andMenuTypeLessThanOrEqualTo(Integer value) {
            addCriterion("menu_type <=", value, "menuType");
            return (Criteria) this;
        }

        public Criteria andMenuTypeIn(List<Integer> values) {
            addCriterion("menu_type in", values, "menuType");
            return (Criteria) this;
        }

        public Criteria andMenuTypeNotIn(List<Integer> values) {
            addCriterion("menu_type not in", values, "menuType");
            return (Criteria) this;
        }

        public Criteria andMenuTypeBetween(Integer value1, Integer value2) {
            addCriterion("menu_type between", value1, value2, "menuType");
            return (Criteria) this;
        }

        public Criteria andMenuTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("menu_type not between", value1, value2, "menuType");
            return (Criteria) this;
        }

        public Criteria andMenuFlavorIsNull() {
            addCriterion("menu_flavor is null");
            return (Criteria) this;
        }

        public Criteria andMenuFlavorIsNotNull() {
            addCriterion("menu_flavor is not null");
            return (Criteria) this;
        }

        public Criteria andMenuFlavorEqualTo(Integer value) {
            addCriterion("menu_flavor =", value, "menuFlavor");
            return (Criteria) this;
        }

        public Criteria andMenuFlavorNotEqualTo(Integer value) {
            addCriterion("menu_flavor <>", value, "menuFlavor");
            return (Criteria) this;
        }

        public Criteria andMenuFlavorGreaterThan(Integer value) {
            addCriterion("menu_flavor >", value, "menuFlavor");
            return (Criteria) this;
        }

        public Criteria andMenuFlavorGreaterThanOrEqualTo(Integer value) {
            addCriterion("menu_flavor >=", value, "menuFlavor");
            return (Criteria) this;
        }

        public Criteria andMenuFlavorLessThan(Integer value) {
            addCriterion("menu_flavor <", value, "menuFlavor");
            return (Criteria) this;
        }

        public Criteria andMenuFlavorLessThanOrEqualTo(Integer value) {
            addCriterion("menu_flavor <=", value, "menuFlavor");
            return (Criteria) this;
        }

        public Criteria andMenuFlavorIn(List<Integer> values) {
            addCriterion("menu_flavor in", values, "menuFlavor");
            return (Criteria) this;
        }

        public Criteria andMenuFlavorNotIn(List<Integer> values) {
            addCriterion("menu_flavor not in", values, "menuFlavor");
            return (Criteria) this;
        }

        public Criteria andMenuFlavorBetween(Integer value1, Integer value2) {
            addCriterion("menu_flavor between", value1, value2, "menuFlavor");
            return (Criteria) this;
        }

        public Criteria andMenuFlavorNotBetween(Integer value1, Integer value2) {
            addCriterion("menu_flavor not between", value1, value2, "menuFlavor");
            return (Criteria) this;
        }

        public Criteria andMenuStarIsNull() {
            addCriterion("menu_star is null");
            return (Criteria) this;
        }

        public Criteria andMenuStarIsNotNull() {
            addCriterion("menu_star is not null");
            return (Criteria) this;
        }

        public Criteria andMenuStarEqualTo(Integer value) {
            addCriterion("menu_star =", value, "menuStar");
            return (Criteria) this;
        }

        public Criteria andMenuStarNotEqualTo(Integer value) {
            addCriterion("menu_star <>", value, "menuStar");
            return (Criteria) this;
        }

        public Criteria andMenuStarGreaterThan(Integer value) {
            addCriterion("menu_star >", value, "menuStar");
            return (Criteria) this;
        }

        public Criteria andMenuStarGreaterThanOrEqualTo(Integer value) {
            addCriterion("menu_star >=", value, "menuStar");
            return (Criteria) this;
        }

        public Criteria andMenuStarLessThan(Integer value) {
            addCriterion("menu_star <", value, "menuStar");
            return (Criteria) this;
        }

        public Criteria andMenuStarLessThanOrEqualTo(Integer value) {
            addCriterion("menu_star <=", value, "menuStar");
            return (Criteria) this;
        }

        public Criteria andMenuStarIn(List<Integer> values) {
            addCriterion("menu_star in", values, "menuStar");
            return (Criteria) this;
        }

        public Criteria andMenuStarNotIn(List<Integer> values) {
            addCriterion("menu_star not in", values, "menuStar");
            return (Criteria) this;
        }

        public Criteria andMenuStarBetween(Integer value1, Integer value2) {
            addCriterion("menu_star between", value1, value2, "menuStar");
            return (Criteria) this;
        }

        public Criteria andMenuStarNotBetween(Integer value1, Integer value2) {
            addCriterion("menu_star not between", value1, value2, "menuStar");
            return (Criteria) this;
        }

        public Criteria andMenuStarPecentIsNull() {
            addCriterion("menu_star_pecent is null");
            return (Criteria) this;
        }

        public Criteria andMenuStarPecentIsNotNull() {
            addCriterion("menu_star_pecent is not null");
            return (Criteria) this;
        }

        public Criteria andMenuStarPecentEqualTo(BigDecimal value) {
            addCriterion("menu_star_pecent =", value, "menuStarPecent");
            return (Criteria) this;
        }

        public Criteria andMenuStarPecentNotEqualTo(BigDecimal value) {
            addCriterion("menu_star_pecent <>", value, "menuStarPecent");
            return (Criteria) this;
        }

        public Criteria andMenuStarPecentGreaterThan(BigDecimal value) {
            addCriterion("menu_star_pecent >", value, "menuStarPecent");
            return (Criteria) this;
        }

        public Criteria andMenuStarPecentGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("menu_star_pecent >=", value, "menuStarPecent");
            return (Criteria) this;
        }

        public Criteria andMenuStarPecentLessThan(BigDecimal value) {
            addCriterion("menu_star_pecent <", value, "menuStarPecent");
            return (Criteria) this;
        }

        public Criteria andMenuStarPecentLessThanOrEqualTo(BigDecimal value) {
            addCriterion("menu_star_pecent <=", value, "menuStarPecent");
            return (Criteria) this;
        }

        public Criteria andMenuStarPecentIn(List<BigDecimal> values) {
            addCriterion("menu_star_pecent in", values, "menuStarPecent");
            return (Criteria) this;
        }

        public Criteria andMenuStarPecentNotIn(List<BigDecimal> values) {
            addCriterion("menu_star_pecent not in", values, "menuStarPecent");
            return (Criteria) this;
        }

        public Criteria andMenuStarPecentBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("menu_star_pecent between", value1, value2, "menuStarPecent");
            return (Criteria) this;
        }

        public Criteria andMenuStarPecentNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("menu_star_pecent not between", value1, value2, "menuStarPecent");
            return (Criteria) this;
        }

        public Criteria andMenuDelIsNull() {
            addCriterion("menu_del is null");
            return (Criteria) this;
        }

        public Criteria andMenuDelIsNotNull() {
            addCriterion("menu_del is not null");
            return (Criteria) this;
        }

        public Criteria andMenuDelEqualTo(Integer value) {
            addCriterion("menu_del =", value, "menuDel");
            return (Criteria) this;
        }

        public Criteria andMenuDelNotEqualTo(Integer value) {
            addCriterion("menu_del <>", value, "menuDel");
            return (Criteria) this;
        }

        public Criteria andMenuDelGreaterThan(Integer value) {
            addCriterion("menu_del >", value, "menuDel");
            return (Criteria) this;
        }

        public Criteria andMenuDelGreaterThanOrEqualTo(Integer value) {
            addCriterion("menu_del >=", value, "menuDel");
            return (Criteria) this;
        }

        public Criteria andMenuDelLessThan(Integer value) {
            addCriterion("menu_del <", value, "menuDel");
            return (Criteria) this;
        }

        public Criteria andMenuDelLessThanOrEqualTo(Integer value) {
            addCriterion("menu_del <=", value, "menuDel");
            return (Criteria) this;
        }

        public Criteria andMenuDelIn(List<Integer> values) {
            addCriterion("menu_del in", values, "menuDel");
            return (Criteria) this;
        }

        public Criteria andMenuDelNotIn(List<Integer> values) {
            addCriterion("menu_del not in", values, "menuDel");
            return (Criteria) this;
        }

        public Criteria andMenuDelBetween(Integer value1, Integer value2) {
            addCriterion("menu_del between", value1, value2, "menuDel");
            return (Criteria) this;
        }

        public Criteria andMenuDelNotBetween(Integer value1, Integer value2) {
            addCriterion("menu_del not between", value1, value2, "menuDel");
            return (Criteria) this;
        }
    }

    /**
     * 类注释
     * Criteria
     * 数据库表：menu
     */
    public static class Criteria extends GeneratedCriteria {


        protected Criteria() {
            super();
        }
    }

    /**
     * 菜品信息
     * Criterion
     * 数据库表：menu
     */
    public static class Criterion {

        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}