package com.zdb.demo.entity;

import java.io.Serializable;

/**
 * 菜品收藏表
 * MenuCollect
 * 数据库表：menu_collect
 */
public class MenuCollect implements Serializable {

    /**
     * 主键id
     * 表字段 : menu_collect.menu_collect_id
     */
    private Integer menuCollectId;

    /**
     * 用户id
     * 表字段 : menu_collect.user_id
     */
    private Integer userId;

    /**
     * 菜品id
     * 表字段 : menu_collect.menu_id
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu_collect
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键id 字段:menu_collect.menu_collect_id
     *
     * @return menu_collect.menu_collect_id, 主键id
     */
    public Integer getMenuCollectId() {
        return menuCollectId;
    }

    /**
     * 设置 主键id 字段:menu_collect.menu_collect_id
     *
     * @param menuCollectId the value for menu_collect.menu_collect_id, 主键id
     */
    public void setMenuCollectId(Integer menuCollectId) {
        this.menuCollectId = menuCollectId;
    }

    /**
     * 获取 用户id 字段:menu_collect.user_id
     *
     * @return menu_collect.user_id, 用户id
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * 设置 用户id 字段:menu_collect.user_id
     *
     * @param userId the value for menu_collect.user_id, 用户id
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * 获取 菜品id 字段:menu_collect.menu_id
     *
     * @return menu_collect.menu_id, 菜品id
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * 设置 菜品id 字段:menu_collect.menu_id
     *
     * @param menuId the value for menu_collect.menu_id, 菜品id
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }
}