package com.zdb.demo.entity;

import java.io.Serializable;

/**
 * 菜品类型表
 * MenuType
 * 数据库表：menu_type
 */
public class MenuType implements Serializable {

    /**
     * 商品类型主键
     * 表字段 : menu_type.menu_type_id
     */
    private Integer menuTypeId;

    /**
     * 菜品类型名称
     * 表字段 : menu_type.menu_type_name
     */
    private String menuTypeName;

    /**
     * 权重
     * 表字段 : menu_type.menu_type_weight
     */
    private Integer menuTypeWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu_type
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 商品类型主键 字段:menu_type.menu_type_id
     *
     * @return menu_type.menu_type_id, 商品类型主键
     */
    public Integer getMenuTypeId() {
        return menuTypeId;
    }

    /**
     * 设置 商品类型主键 字段:menu_type.menu_type_id
     *
     * @param menuTypeId the value for menu_type.menu_type_id, 商品类型主键
     */
    public void setMenuTypeId(Integer menuTypeId) {
        this.menuTypeId = menuTypeId;
    }

    /**
     * 获取 菜品类型名称 字段:menu_type.menu_type_name
     *
     * @return menu_type.menu_type_name, 菜品类型名称
     */
    public String getMenuTypeName() {
        return menuTypeName;
    }

    /**
     * 设置 菜品类型名称 字段:menu_type.menu_type_name
     *
     * @param menuTypeName the value for menu_type.menu_type_name, 菜品类型名称
     */
    public void setMenuTypeName(String menuTypeName) {
        this.menuTypeName = menuTypeName == null ? null : menuTypeName.trim();
    }

    /**
     * 获取 权重 字段:menu_type.menu_type_weight
     *
     * @return menu_type.menu_type_weight, 权重
     */
    public Integer getMenuTypeWeight() {
        return menuTypeWeight;
    }

    /**
     * 设置 权重 字段:menu_type.menu_type_weight
     *
     * @param menuTypeWeight the value for menu_type.menu_type_weight, 权重
     */
    public void setMenuTypeWeight(Integer menuTypeWeight) {
        this.menuTypeWeight = menuTypeWeight;
    }
}