package com.zdb.demo.entity;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * 菜品信息
 * Menu
 * 数据库表：menu
 */
public class Menu implements Serializable {

    /**
     * 菜品id
     * 表字段 : menu.menu_id
     */
    private Integer menuId;

    /**
     * 商家关联id
     * 表字段 : menu.menu_store_id
     */
    private Integer menuStoreId;

    /**
     * 菜品名称
     * 表字段 : menu.menu_name
     */
    private String menuName;

    /**
     * 菜品价格
     * 表字段 : menu.menu_price
     */
    private BigDecimal menuPrice;

    /**
     * 菜品折扣
     * 表字段 : menu.menu_discount
     */
    private BigDecimal menuDiscount;

    /**
     * 菜品销量
     * 表字段 : menu.menu_sales
     */
    private Long menuSales;

    /**
     * 菜品图片
     * 表字段 : menu.menu_img
     */
    private String menuImg;

    /**
     * 菜品类型
     * 表字段 : menu.menu_type
     */
    private Integer menuType;

    /**
     * 菜品口味 1不辣/2微辣/3中辣/特辣
     * 表字段 : menu.menu_flavor
     */
    private Integer menuFlavor;

    /**
     * 好评量
     * 表字段 : menu.menu_star
     */
    private Integer menuStar;

    /**
     * 好评百分比
     * 表字段 : menu.menu_star_pecent
     */
    private BigDecimal menuStarPecent;

    /**
     * 删除 0未删除/1已删除
     * 表字段 : menu.menu_del
     */
    private Integer menuDel;

    /**
     * 招牌 0非招牌/1招牌
     * 表字段 : menu.menu_is_nice
     */
    private Integer menuIsNice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 菜品id 字段:menu.menu_id
     *
     * @return menu.menu_id, 菜品id
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * 设置 菜品id 字段:menu.menu_id
     *
     * @param menuId the value for menu.menu_id, 菜品id
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * 获取 商家关联id 字段:menu.menu_store_id
     *
     * @return menu.menu_store_id, 商家关联id
     */
    public Integer getMenuStoreId() {
        return menuStoreId;
    }

    /**
     * 设置 商家关联id 字段:menu.menu_store_id
     *
     * @param menuStoreId the value for menu.menu_store_id, 商家关联id
     */
    public void setMenuStoreId(Integer menuStoreId) {
        this.menuStoreId = menuStoreId;
    }

    /**
     * 获取 菜品名称 字段:menu.menu_name
     *
     * @return menu.menu_name, 菜品名称
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * 设置 菜品名称 字段:menu.menu_name
     *
     * @param menuName the value for menu.menu_name, 菜品名称
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * 获取 菜品价格 字段:menu.menu_price
     *
     * @return menu.menu_price, 菜品价格
     */
    public BigDecimal getMenuPrice() {
        return menuPrice;
    }

    /**
     * 设置 菜品价格 字段:menu.menu_price
     *
     * @param menuPrice the value for menu.menu_price, 菜品价格
     */
    public void setMenuPrice(BigDecimal menuPrice) {
        this.menuPrice = menuPrice;
    }

    /**
     * 获取 菜品折扣 字段:menu.menu_discount
     *
     * @return menu.menu_discount, 菜品折扣
     */
    public BigDecimal getMenuDiscount() {
        return menuDiscount;
    }

    /**
     * 设置 菜品折扣 字段:menu.menu_discount
     *
     * @param menuDiscount the value for menu.menu_discount, 菜品折扣
     */
    public void setMenuDiscount(BigDecimal menuDiscount) {
        this.menuDiscount = menuDiscount;
    }

    /**
     * 获取 菜品销量 字段:menu.menu_sales
     *
     * @return menu.menu_sales, 菜品销量
     */
    public Long getMenuSales() {
        return menuSales;
    }

    /**
     * 设置 菜品销量 字段:menu.menu_sales
     *
     * @param menuSales the value for menu.menu_sales, 菜品销量
     */
    public void setMenuSales(Long menuSales) {
        this.menuSales = menuSales;
    }

    /**
     * 获取 菜品图片 字段:menu.menu_img
     *
     * @return menu.menu_img, 菜品图片
     */
    public String getMenuImg() {
        return menuImg;
    }

    /**
     * 设置 菜品图片 字段:menu.menu_img
     *
     * @param menuImg the value for menu.menu_img, 菜品图片
     */
    public void setMenuImg(String menuImg) {
        this.menuImg = menuImg == null ? null : menuImg.trim();
    }

    /**
     * 获取 菜品类型 字段:menu.menu_type
     *
     * @return menu.menu_type, 菜品类型
     */
    public Integer getMenuType() {
        return menuType;
    }

    /**
     * 设置 菜品类型 字段:menu.menu_type
     *
     * @param menuType the value for menu.menu_type, 菜品类型
     */
    public void setMenuType(Integer menuType) {
        this.menuType = menuType;
    }

    /**
     * 获取 菜品口味 1不辣/2微辣/3中辣/特辣 字段:menu.menu_flavor
     *
     * @return menu.menu_flavor, 菜品口味 1不辣/2微辣/3中辣/特辣
     */
    public Integer getMenuFlavor() {
        return menuFlavor;
    }

    /**
     * 设置 菜品口味 1不辣/2微辣/3中辣/特辣 字段:menu.menu_flavor
     *
     * @param menuFlavor the value for menu.menu_flavor, 菜品口味 1不辣/2微辣/3中辣/特辣
     */
    public void setMenuFlavor(Integer menuFlavor) {
        this.menuFlavor = menuFlavor;
    }

    /**
     * 获取 好评量 字段:menu.menu_star
     *
     * @return menu.menu_star, 好评量
     */
    public Integer getMenuStar() {
        return menuStar;
    }

    /**
     * 设置 好评量 字段:menu.menu_star
     *
     * @param menuStar the value for menu.menu_star, 好评量
     */
    public void setMenuStar(Integer menuStar) {
        this.menuStar = menuStar;
    }

    /**
     * 获取 好评百分比 字段:menu.menu_star_pecent
     *
     * @return menu.menu_star_pecent, 好评百分比
     */
    public BigDecimal getMenuStarPecent() {
        return menuStarPecent;
    }

    /**
     * 设置 好评百分比 字段:menu.menu_star_pecent
     *
     * @param menuStarPecent the value for menu.menu_star_pecent, 好评百分比
     */
    public void setMenuStarPecent(BigDecimal menuStarPecent) {
        this.menuStarPecent = menuStarPecent;
    }

    /**
     * 获取 删除 0未删除/1已删除 字段:menu.menu_del
     *
     * @return menu.menu_del, 删除 0未删除/1已删除
     */
    public Integer getMenuDel() {
        return menuDel;
    }

    /**
     * 设置 删除 0未删除/1已删除 字段:menu.menu_del
     *
     * @param menuDel the value for menu.menu_del, 删除 0未删除/1已删除
     */
    public void setMenuDel(Integer menuDel) {
        this.menuDel = menuDel;
    }

    /**
     * 获取 招牌 0非招牌/1招牌 字段:menu.menu_is_nice
     *
     * @return menu.menu_is_nice, 招牌 0非招牌/1招牌
     */
    public Integer getMenuIsNice() {
        return menuIsNice;
    }

    /**
     * 设置 招牌 0非招牌/1招牌 字段:menu.menu_is_nice
     *
     * @param menuIsNice the value for menu.menu_is_nice, 招牌 0非招牌/1招牌
     */
    public void setMenuIsNice(Integer menuIsNice) {
        this.menuIsNice = menuIsNice;
    }
}