package com.zdb.demo.entity;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * 订单中菜品信息
 * OrderMenu
 * 数据库表：order_menu
 */
public class OrderMenu implements Serializable {

    /**
     * 主键id
     * 表字段 : order_menu.order_menu_id
     */
    private Integer orderMenuId;

    /**
     * 订单id
     * 表字段 : order_menu.order_id
     */
    private Integer orderId;

    /**
     * 菜品id
     * 表字段 : order_menu.menu_id
     */
    private Integer menuId;

    /**
     * 菜品数量
     * 表字段 : order_menu.menu_num
     */
    private Integer menuNum;

    /**
     * 该菜品的总价
     * 表字段 : order_menu.order_menu_price
     */
    private BigDecimal orderMenuPrice;

    /**
     * 菜品名称
     */
    private String menuName;

    /**
     * 辣的程度 0不辣/1微辣/2中辣/3特辣/4魔鬼辣
     * 表字段 : order_menu.menu_pepper
     */
    private Integer menuPepper;

    /**
     * 分量 0小份/1中份/2大份
     * 表字段 : order_menu.menu_weight
     */
    private Integer menuWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_menu
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键id 字段:order_menu.order_menu_id
     *
     * @return order_menu.order_menu_id, 主键id
     */
    public Integer getOrderMenuId() {
        return orderMenuId;
    }

    /**
     * 设置 主键id 字段:order_menu.order_menu_id
     *
     * @param orderMenuId the value for order_menu.order_menu_id, 主键id
     */
    public void setOrderMenuId(Integer orderMenuId) {
        this.orderMenuId = orderMenuId;
    }

    /**
     * 获取 订单id 字段:order_menu.order_id
     *
     * @return order_menu.order_id, 订单id
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * 设置 订单id 字段:order_menu.order_id
     *
     * @param orderId the value for order_menu.order_id, 订单id
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * 获取 菜品id 字段:order_menu.menu_id
     *
     * @return order_menu.menu_id, 菜品id
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * 设置 菜品id 字段:order_menu.menu_id
     *
     * @param menuId the value for order_menu.menu_id, 菜品id
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * 获取 菜品数量 字段:order_menu.menu_num
     *
     * @return order_menu.menu_num, 菜品数量
     */
    public Integer getMenuNum() {
        return menuNum;
    }

    /**
     * 设置 菜品数量 字段:order_menu.menu_num
     *
     * @param menuNum the value for order_menu.menu_num, 菜品数量
     */
    public void setMenuNum(Integer menuNum) {
        this.menuNum = menuNum;
    }

    /**
     * 获取 该菜品的总价 字段:order_menu.order_menu_price
     *
     * @return order_menu.order_menu_price, 该菜品的总价
     */
    public BigDecimal getOrderMenuPrice() {
        return orderMenuPrice;
    }

    /**
     * 设置 该菜品的总价 字段:order_menu.order_menu_price
     *
     * @param orderMenuPrice the value for order_menu.order_menu_price, 该菜品的总价
     */
    public void setOrderMenuPrice(BigDecimal orderMenuPrice) {
        this.orderMenuPrice = orderMenuPrice;
    }

    public String getMenuName() {
        return menuName;
    }

    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }
    /**
     * 获取 辣的程度 0不辣/1微辣/2中辣/3特辣/4魔鬼辣 字段:order_menu.menu_pepper
     *
     * @return order_menu.menu_pepper, 辣的程度 0不辣/1微辣/2中辣/3特辣/4魔鬼辣
     */
    public Integer getMenuPepper() {
        return menuPepper;
    }

    /**
     * 设置 辣的程度 0不辣/1微辣/2中辣/3特辣/4魔鬼辣 字段:order_menu.menu_pepper
     *
     * @param menuPepper the value for order_menu.menu_pepper, 辣的程度 0不辣/1微辣/2中辣/3特辣/4魔鬼辣
     */
    public void setMenuPepper(Integer menuPepper) {
        this.menuPepper = menuPepper;
    }

    /**
     * 获取 分量 0小份/1中份/2大份 字段:order_menu.menu_weight
     *
     * @return order_menu.menu_weight, 分量 0小份/1中份/2大份
     */
    public Integer getMenuWeight() {
        return menuWeight;
    }

    /**
     * 设置 分量 0小份/1中份/2大份 字段:order_menu.menu_weight
     *
     * @param menuWeight the value for order_menu.menu_weight, 分量 0小份/1中份/2大份
     */
    public void setMenuWeight(Integer menuWeight) {
        this.menuWeight = menuWeight;
    }
}