package com.zdb.demo.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrdersExample {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbggenerated
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbggenerated
     */
    protected Integer limitEnd;

    /**
     *  构造查询条件,orders
     */
    public OrdersExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *  设置排序字段,orders
     *
     * @param orderByClause 排序字段
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *  获取排序字段,orders
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *  设置过滤重复数据,orders
     *
     * @param distinct 是否过滤重复数据
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *  是否过滤重复数据,orders
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *  获取当前的查询条件实例,orders
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * ,orders
     *
     * @param criteria 过滤条件实例
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * ,orders
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *  创建一个查询条件,orders
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *  内部构建查询条件对象,orders
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *  清除查询条件,orders
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * ,orders
     *
     * @param limitStart
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * ,orders
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * ,orders
     *
     * @param limitEnd
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * ,orders
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * 订单
     * GeneratedCriteria
     * 数据库表：orders
     */
    protected abstract static class GeneratedCriteria {

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(Integer value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(Integer value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(Integer value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(Integer value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Integer value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<Integer> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<Integer> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(Integer value1, Integer value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderUserIdIsNull() {
            addCriterion("order_user_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderUserIdIsNotNull() {
            addCriterion("order_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderUserIdEqualTo(Integer value) {
            addCriterion("order_user_id =", value, "orderUserId");
            return (Criteria) this;
        }

        public Criteria andOrderUserIdNotEqualTo(Integer value) {
            addCriterion("order_user_id <>", value, "orderUserId");
            return (Criteria) this;
        }

        public Criteria andOrderUserIdGreaterThan(Integer value) {
            addCriterion("order_user_id >", value, "orderUserId");
            return (Criteria) this;
        }

        public Criteria andOrderUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_user_id >=", value, "orderUserId");
            return (Criteria) this;
        }

        public Criteria andOrderUserIdLessThan(Integer value) {
            addCriterion("order_user_id <", value, "orderUserId");
            return (Criteria) this;
        }

        public Criteria andOrderUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("order_user_id <=", value, "orderUserId");
            return (Criteria) this;
        }

        public Criteria andOrderUserIdIn(List<Integer> values) {
            addCriterion("order_user_id in", values, "orderUserId");
            return (Criteria) this;
        }

        public Criteria andOrderUserIdNotIn(List<Integer> values) {
            addCriterion("order_user_id not in", values, "orderUserId");
            return (Criteria) this;
        }

        public Criteria andOrderUserIdBetween(Integer value1, Integer value2) {
            addCriterion("order_user_id between", value1, value2, "orderUserId");
            return (Criteria) this;
        }

        public Criteria andOrderUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("order_user_id not between", value1, value2, "orderUserId");
            return (Criteria) this;
        }

        public Criteria andOrderCreateTimeIsNull() {
            addCriterion("order_create_time is null");
            return (Criteria) this;
        }

        public Criteria andOrderCreateTimeIsNotNull() {
            addCriterion("order_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andOrderCreateTimeEqualTo(Date value) {
            addCriterion("order_create_time =", value, "orderCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderCreateTimeNotEqualTo(Date value) {
            addCriterion("order_create_time <>", value, "orderCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderCreateTimeGreaterThan(Date value) {
            addCriterion("order_create_time >", value, "orderCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("order_create_time >=", value, "orderCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderCreateTimeLessThan(Date value) {
            addCriterion("order_create_time <", value, "orderCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("order_create_time <=", value, "orderCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderCreateTimeIn(List<Date> values) {
            addCriterion("order_create_time in", values, "orderCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderCreateTimeNotIn(List<Date> values) {
            addCriterion("order_create_time not in", values, "orderCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderCreateTimeBetween(Date value1, Date value2) {
            addCriterion("order_create_time between", value1, value2, "orderCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("order_create_time not between", value1, value2, "orderCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderStateIsNull() {
            addCriterion("order_state is null");
            return (Criteria) this;
        }

        public Criteria andOrderStateIsNotNull() {
            addCriterion("order_state is not null");
            return (Criteria) this;
        }

        public Criteria andOrderStateEqualTo(Integer value) {
            addCriterion("order_state =", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateNotEqualTo(Integer value) {
            addCriterion("order_state <>", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateGreaterThan(Integer value) {
            addCriterion("order_state >", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_state >=", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateLessThan(Integer value) {
            addCriterion("order_state <", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateLessThanOrEqualTo(Integer value) {
            addCriterion("order_state <=", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateIn(List<Integer> values) {
            addCriterion("order_state in", values, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateNotIn(List<Integer> values) {
            addCriterion("order_state not in", values, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateBetween(Integer value1, Integer value2) {
            addCriterion("order_state between", value1, value2, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateNotBetween(Integer value1, Integer value2) {
            addCriterion("order_state not between", value1, value2, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStoreIdIsNull() {
            addCriterion("order_store_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderStoreIdIsNotNull() {
            addCriterion("order_store_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderStoreIdEqualTo(Integer value) {
            addCriterion("order_store_id =", value, "orderStoreId");
            return (Criteria) this;
        }

        public Criteria andOrderStoreIdNotEqualTo(Integer value) {
            addCriterion("order_store_id <>", value, "orderStoreId");
            return (Criteria) this;
        }

        public Criteria andOrderStoreIdGreaterThan(Integer value) {
            addCriterion("order_store_id >", value, "orderStoreId");
            return (Criteria) this;
        }

        public Criteria andOrderStoreIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_store_id >=", value, "orderStoreId");
            return (Criteria) this;
        }

        public Criteria andOrderStoreIdLessThan(Integer value) {
            addCriterion("order_store_id <", value, "orderStoreId");
            return (Criteria) this;
        }

        public Criteria andOrderStoreIdLessThanOrEqualTo(Integer value) {
            addCriterion("order_store_id <=", value, "orderStoreId");
            return (Criteria) this;
        }

        public Criteria andOrderStoreIdIn(List<Integer> values) {
            addCriterion("order_store_id in", values, "orderStoreId");
            return (Criteria) this;
        }

        public Criteria andOrderStoreIdNotIn(List<Integer> values) {
            addCriterion("order_store_id not in", values, "orderStoreId");
            return (Criteria) this;
        }

        public Criteria andOrderStoreIdBetween(Integer value1, Integer value2) {
            addCriterion("order_store_id between", value1, value2, "orderStoreId");
            return (Criteria) this;
        }

        public Criteria andOrderStoreIdNotBetween(Integer value1, Integer value2) {
            addCriterion("order_store_id not between", value1, value2, "orderStoreId");
            return (Criteria) this;
        }

        public Criteria andOrderSumPriceIsNull() {
            addCriterion("order_sum_price is null");
            return (Criteria) this;
        }

        public Criteria andOrderSumPriceIsNotNull() {
            addCriterion("order_sum_price is not null");
            return (Criteria) this;
        }

        public Criteria andOrderSumPriceEqualTo(BigDecimal value) {
            addCriterion("order_sum_price =", value, "orderSumPrice");
            return (Criteria) this;
        }

        public Criteria andOrderSumPriceNotEqualTo(BigDecimal value) {
            addCriterion("order_sum_price <>", value, "orderSumPrice");
            return (Criteria) this;
        }

        public Criteria andOrderSumPriceGreaterThan(BigDecimal value) {
            addCriterion("order_sum_price >", value, "orderSumPrice");
            return (Criteria) this;
        }

        public Criteria andOrderSumPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("order_sum_price >=", value, "orderSumPrice");
            return (Criteria) this;
        }

        public Criteria andOrderSumPriceLessThan(BigDecimal value) {
            addCriterion("order_sum_price <", value, "orderSumPrice");
            return (Criteria) this;
        }

        public Criteria andOrderSumPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("order_sum_price <=", value, "orderSumPrice");
            return (Criteria) this;
        }

        public Criteria andOrderSumPriceIn(List<BigDecimal> values) {
            addCriterion("order_sum_price in", values, "orderSumPrice");
            return (Criteria) this;
        }

        public Criteria andOrderSumPriceNotIn(List<BigDecimal> values) {
            addCriterion("order_sum_price not in", values, "orderSumPrice");
            return (Criteria) this;
        }

        public Criteria andOrderSumPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("order_sum_price between", value1, value2, "orderSumPrice");
            return (Criteria) this;
        }

        public Criteria andOrderSumPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("order_sum_price not between", value1, value2, "orderSumPrice");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkIsNull() {
            addCriterion("order_remark is null");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkIsNotNull() {
            addCriterion("order_remark is not null");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkEqualTo(String value) {
            addCriterion("order_remark =", value, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkNotEqualTo(String value) {
            addCriterion("order_remark <>", value, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkGreaterThan(String value) {
            addCriterion("order_remark >", value, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("order_remark >=", value, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkLessThan(String value) {
            addCriterion("order_remark <", value, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkLessThanOrEqualTo(String value) {
            addCriterion("order_remark <=", value, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkLike(String value) {
            addCriterion("order_remark like", value, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkNotLike(String value) {
            addCriterion("order_remark not like", value, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkIn(List<String> values) {
            addCriterion("order_remark in", values, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkNotIn(List<String> values) {
            addCriterion("order_remark not in", values, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkBetween(String value1, String value2) {
            addCriterion("order_remark between", value1, value2, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkNotBetween(String value1, String value2) {
            addCriterion("order_remark not between", value1, value2, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderEvaluateIsNull() {
            addCriterion("order_evaluate is null");
            return (Criteria) this;
        }

        public Criteria andOrderEvaluateIsNotNull() {
            addCriterion("order_evaluate is not null");
            return (Criteria) this;
        }

        public Criteria andOrderEvaluateEqualTo(String value) {
            addCriterion("order_evaluate =", value, "orderEvaluate");
            return (Criteria) this;
        }

        public Criteria andOrderEvaluateNotEqualTo(String value) {
            addCriterion("order_evaluate <>", value, "orderEvaluate");
            return (Criteria) this;
        }

        public Criteria andOrderEvaluateGreaterThan(String value) {
            addCriterion("order_evaluate >", value, "orderEvaluate");
            return (Criteria) this;
        }

        public Criteria andOrderEvaluateGreaterThanOrEqualTo(String value) {
            addCriterion("order_evaluate >=", value, "orderEvaluate");
            return (Criteria) this;
        }

        public Criteria andOrderEvaluateLessThan(String value) {
            addCriterion("order_evaluate <", value, "orderEvaluate");
            return (Criteria) this;
        }

        public Criteria andOrderEvaluateLessThanOrEqualTo(String value) {
            addCriterion("order_evaluate <=", value, "orderEvaluate");
            return (Criteria) this;
        }

        public Criteria andOrderEvaluateLike(String value) {
            addCriterion("order_evaluate like", value, "orderEvaluate");
            return (Criteria) this;
        }

        public Criteria andOrderEvaluateNotLike(String value) {
            addCriterion("order_evaluate not like", value, "orderEvaluate");
            return (Criteria) this;
        }

        public Criteria andOrderEvaluateIn(List<String> values) {
            addCriterion("order_evaluate in", values, "orderEvaluate");
            return (Criteria) this;
        }

        public Criteria andOrderEvaluateNotIn(List<String> values) {
            addCriterion("order_evaluate not in", values, "orderEvaluate");
            return (Criteria) this;
        }

        public Criteria andOrderEvaluateBetween(String value1, String value2) {
            addCriterion("order_evaluate between", value1, value2, "orderEvaluate");
            return (Criteria) this;
        }

        public Criteria andOrderEvaluateNotBetween(String value1, String value2) {
            addCriterion("order_evaluate not between", value1, value2, "orderEvaluate");
            return (Criteria) this;
        }

        public Criteria andOrderDelIsNull() {
            addCriterion("order_del is null");
            return (Criteria) this;
        }

        public Criteria andOrderDelIsNotNull() {
            addCriterion("order_del is not null");
            return (Criteria) this;
        }

        public Criteria andOrderDelEqualTo(Integer value) {
            addCriterion("order_del =", value, "orderDel");
            return (Criteria) this;
        }

        public Criteria andOrderDelNotEqualTo(Integer value) {
            addCriterion("order_del <>", value, "orderDel");
            return (Criteria) this;
        }

        public Criteria andOrderDelGreaterThan(Integer value) {
            addCriterion("order_del >", value, "orderDel");
            return (Criteria) this;
        }

        public Criteria andOrderDelGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_del >=", value, "orderDel");
            return (Criteria) this;
        }

        public Criteria andOrderDelLessThan(Integer value) {
            addCriterion("order_del <", value, "orderDel");
            return (Criteria) this;
        }

        public Criteria andOrderDelLessThanOrEqualTo(Integer value) {
            addCriterion("order_del <=", value, "orderDel");
            return (Criteria) this;
        }

        public Criteria andOrderDelIn(List<Integer> values) {
            addCriterion("order_del in", values, "orderDel");
            return (Criteria) this;
        }

        public Criteria andOrderDelNotIn(List<Integer> values) {
            addCriterion("order_del not in", values, "orderDel");
            return (Criteria) this;
        }

        public Criteria andOrderDelBetween(Integer value1, Integer value2) {
            addCriterion("order_del between", value1, value2, "orderDel");
            return (Criteria) this;
        }

        public Criteria andOrderDelNotBetween(Integer value1, Integer value2) {
            addCriterion("order_del not between", value1, value2, "orderDel");
            return (Criteria) this;
        }
    }

    /**
     * 类注释
     * Criteria
     * 数据库表：orders
     */
    public static class Criteria extends GeneratedCriteria {


        protected Criteria() {
            super();
        }
    }

    /**
     * 订单
     * Criterion
     * 数据库表：orders
     */
    public static class Criterion {

        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}