package com.zdb.demo.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class OrderMenuExample {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_menu
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_menu
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_menu
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_menu
     *
     * @mbggenerated
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_menu
     *
     * @mbggenerated
     */
    protected Integer limitEnd;

    /**
     *  构造查询条件,order_menu
     */
    public OrderMenuExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *  设置排序字段,order_menu
     *
     * @param orderByClause 排序字段
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *  获取排序字段,order_menu
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *  设置过滤重复数据,order_menu
     *
     * @param distinct 是否过滤重复数据
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *  是否过滤重复数据,order_menu
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *  获取当前的查询条件实例,order_menu
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * ,order_menu
     *
     * @param criteria 过滤条件实例
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * ,order_menu
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *  创建一个查询条件,order_menu
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *  内部构建查询条件对象,order_menu
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *  清除查询条件,order_menu
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * ,order_menu
     *
     * @param limitStart
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * ,order_menu
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * ,order_menu
     *
     * @param limitEnd
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * ,order_menu
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * 订单中菜品信息
     * GeneratedCriteria
     * 数据库表：order_menu
     */
    protected abstract static class GeneratedCriteria {

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderMenuIdIsNull() {
            addCriterion("order_menu_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderMenuIdIsNotNull() {
            addCriterion("order_menu_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderMenuIdEqualTo(Integer value) {
            addCriterion("order_menu_id =", value, "orderMenuId");
            return (Criteria) this;
        }

        public Criteria andOrderMenuIdNotEqualTo(Integer value) {
            addCriterion("order_menu_id <>", value, "orderMenuId");
            return (Criteria) this;
        }

        public Criteria andOrderMenuIdGreaterThan(Integer value) {
            addCriterion("order_menu_id >", value, "orderMenuId");
            return (Criteria) this;
        }

        public Criteria andOrderMenuIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_menu_id >=", value, "orderMenuId");
            return (Criteria) this;
        }

        public Criteria andOrderMenuIdLessThan(Integer value) {
            addCriterion("order_menu_id <", value, "orderMenuId");
            return (Criteria) this;
        }

        public Criteria andOrderMenuIdLessThanOrEqualTo(Integer value) {
            addCriterion("order_menu_id <=", value, "orderMenuId");
            return (Criteria) this;
        }

        public Criteria andOrderMenuIdIn(List<Integer> values) {
            addCriterion("order_menu_id in", values, "orderMenuId");
            return (Criteria) this;
        }

        public Criteria andOrderMenuIdNotIn(List<Integer> values) {
            addCriterion("order_menu_id not in", values, "orderMenuId");
            return (Criteria) this;
        }

        public Criteria andOrderMenuIdBetween(Integer value1, Integer value2) {
            addCriterion("order_menu_id between", value1, value2, "orderMenuId");
            return (Criteria) this;
        }

        public Criteria andOrderMenuIdNotBetween(Integer value1, Integer value2) {
            addCriterion("order_menu_id not between", value1, value2, "orderMenuId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(Integer value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(Integer value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(Integer value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(Integer value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Integer value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<Integer> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<Integer> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(Integer value1, Integer value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andMenuIdIsNull() {
            addCriterion("menu_id is null");
            return (Criteria) this;
        }

        public Criteria andMenuIdIsNotNull() {
            addCriterion("menu_id is not null");
            return (Criteria) this;
        }

        public Criteria andMenuIdEqualTo(Integer value) {
            addCriterion("menu_id =", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotEqualTo(Integer value) {
            addCriterion("menu_id <>", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdGreaterThan(Integer value) {
            addCriterion("menu_id >", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("menu_id >=", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdLessThan(Integer value) {
            addCriterion("menu_id <", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdLessThanOrEqualTo(Integer value) {
            addCriterion("menu_id <=", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdIn(List<Integer> values) {
            addCriterion("menu_id in", values, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotIn(List<Integer> values) {
            addCriterion("menu_id not in", values, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdBetween(Integer value1, Integer value2) {
            addCriterion("menu_id between", value1, value2, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotBetween(Integer value1, Integer value2) {
            addCriterion("menu_id not between", value1, value2, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuNumIsNull() {
            addCriterion("menu_num is null");
            return (Criteria) this;
        }

        public Criteria andMenuNumIsNotNull() {
            addCriterion("menu_num is not null");
            return (Criteria) this;
        }

        public Criteria andMenuNumEqualTo(Integer value) {
            addCriterion("menu_num =", value, "menuNum");
            return (Criteria) this;
        }

        public Criteria andMenuNumNotEqualTo(Integer value) {
            addCriterion("menu_num <>", value, "menuNum");
            return (Criteria) this;
        }

        public Criteria andMenuNumGreaterThan(Integer value) {
            addCriterion("menu_num >", value, "menuNum");
            return (Criteria) this;
        }

        public Criteria andMenuNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("menu_num >=", value, "menuNum");
            return (Criteria) this;
        }

        public Criteria andMenuNumLessThan(Integer value) {
            addCriterion("menu_num <", value, "menuNum");
            return (Criteria) this;
        }

        public Criteria andMenuNumLessThanOrEqualTo(Integer value) {
            addCriterion("menu_num <=", value, "menuNum");
            return (Criteria) this;
        }

        public Criteria andMenuNumIn(List<Integer> values) {
            addCriterion("menu_num in", values, "menuNum");
            return (Criteria) this;
        }

        public Criteria andMenuNumNotIn(List<Integer> values) {
            addCriterion("menu_num not in", values, "menuNum");
            return (Criteria) this;
        }

        public Criteria andMenuNumBetween(Integer value1, Integer value2) {
            addCriterion("menu_num between", value1, value2, "menuNum");
            return (Criteria) this;
        }

        public Criteria andMenuNumNotBetween(Integer value1, Integer value2) {
            addCriterion("menu_num not between", value1, value2, "menuNum");
            return (Criteria) this;
        }

        public Criteria andOrderMenuPriceIsNull() {
            addCriterion("order_menu_price is null");
            return (Criteria) this;
        }

        public Criteria andOrderMenuPriceIsNotNull() {
            addCriterion("order_menu_price is not null");
            return (Criteria) this;
        }

        public Criteria andOrderMenuPriceEqualTo(BigDecimal value) {
            addCriterion("order_menu_price =", value, "orderMenuPrice");
            return (Criteria) this;
        }

        public Criteria andOrderMenuPriceNotEqualTo(BigDecimal value) {
            addCriterion("order_menu_price <>", value, "orderMenuPrice");
            return (Criteria) this;
        }

        public Criteria andOrderMenuPriceGreaterThan(BigDecimal value) {
            addCriterion("order_menu_price >", value, "orderMenuPrice");
            return (Criteria) this;
        }

        public Criteria andOrderMenuPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("order_menu_price >=", value, "orderMenuPrice");
            return (Criteria) this;
        }

        public Criteria andOrderMenuPriceLessThan(BigDecimal value) {
            addCriterion("order_menu_price <", value, "orderMenuPrice");
            return (Criteria) this;
        }

        public Criteria andOrderMenuPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("order_menu_price <=", value, "orderMenuPrice");
            return (Criteria) this;
        }

        public Criteria andOrderMenuPriceIn(List<BigDecimal> values) {
            addCriterion("order_menu_price in", values, "orderMenuPrice");
            return (Criteria) this;
        }

        public Criteria andOrderMenuPriceNotIn(List<BigDecimal> values) {
            addCriterion("order_menu_price not in", values, "orderMenuPrice");
            return (Criteria) this;
        }

        public Criteria andOrderMenuPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("order_menu_price between", value1, value2, "orderMenuPrice");
            return (Criteria) this;
        }

        public Criteria andOrderMenuPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("order_menu_price not between", value1, value2, "orderMenuPrice");
            return (Criteria) this;
        }
        public Criteria andMenuPepperIsNull() {
            addCriterion("menu_pepper is null");
            return (Criteria) this;
        }

        public Criteria andMenuPepperIsNotNull() {
            addCriterion("menu_pepper is not null");
            return (Criteria) this;
        }

        public Criteria andMenuPepperEqualTo(Integer value) {
            addCriterion("menu_pepper =", value, "menuPepper");
            return (Criteria) this;
        }

        public Criteria andMenuPepperNotEqualTo(Integer value) {
            addCriterion("menu_pepper <>", value, "menuPepper");
            return (Criteria) this;
        }

        public Criteria andMenuPepperGreaterThan(Integer value) {
            addCriterion("menu_pepper >", value, "menuPepper");
            return (Criteria) this;
        }

        public Criteria andMenuPepperGreaterThanOrEqualTo(Integer value) {
            addCriterion("menu_pepper >=", value, "menuPepper");
            return (Criteria) this;
        }

        public Criteria andMenuPepperLessThan(Integer value) {
            addCriterion("menu_pepper <", value, "menuPepper");
            return (Criteria) this;
        }

        public Criteria andMenuPepperLessThanOrEqualTo(Integer value) {
            addCriterion("menu_pepper <=", value, "menuPepper");
            return (Criteria) this;
        }

        public Criteria andMenuPepperIn(List<Integer> values) {
            addCriterion("menu_pepper in", values, "menuPepper");
            return (Criteria) this;
        }

        public Criteria andMenuPepperNotIn(List<Integer> values) {
            addCriterion("menu_pepper not in", values, "menuPepper");
            return (Criteria) this;
        }

        public Criteria andMenuPepperBetween(Integer value1, Integer value2) {
            addCriterion("menu_pepper between", value1, value2, "menuPepper");
            return (Criteria) this;
        }

        public Criteria andMenuPepperNotBetween(Integer value1, Integer value2) {
            addCriterion("menu_pepper not between", value1, value2, "menuPepper");
            return (Criteria) this;
        }

        public Criteria andMenuWeightIsNull() {
            addCriterion("menu_weight is null");
            return (Criteria) this;
        }

        public Criteria andMenuWeightIsNotNull() {
            addCriterion("menu_weight is not null");
            return (Criteria) this;
        }

        public Criteria andMenuWeightEqualTo(Integer value) {
            addCriterion("menu_weight =", value, "menuWeight");
            return (Criteria) this;
        }

        public Criteria andMenuWeightNotEqualTo(Integer value) {
            addCriterion("menu_weight <>", value, "menuWeight");
            return (Criteria) this;
        }

        public Criteria andMenuWeightGreaterThan(Integer value) {
            addCriterion("menu_weight >", value, "menuWeight");
            return (Criteria) this;
        }

        public Criteria andMenuWeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("menu_weight >=", value, "menuWeight");
            return (Criteria) this;
        }

        public Criteria andMenuWeightLessThan(Integer value) {
            addCriterion("menu_weight <", value, "menuWeight");
            return (Criteria) this;
        }

        public Criteria andMenuWeightLessThanOrEqualTo(Integer value) {
            addCriterion("menu_weight <=", value, "menuWeight");
            return (Criteria) this;
        }

        public Criteria andMenuWeightIn(List<Integer> values) {
            addCriterion("menu_weight in", values, "menuWeight");
            return (Criteria) this;
        }

        public Criteria andMenuWeightNotIn(List<Integer> values) {
            addCriterion("menu_weight not in", values, "menuWeight");
            return (Criteria) this;
        }

        public Criteria andMenuWeightBetween(Integer value1, Integer value2) {
            addCriterion("menu_weight between", value1, value2, "menuWeight");
            return (Criteria) this;
        }

        public Criteria andMenuWeightNotBetween(Integer value1, Integer value2) {
            addCriterion("menu_weight not between", value1, value2, "menuWeight");
            return (Criteria) this;
        }
    }

    /**
     * 类注释
     * Criteria
     * 数据库表：order_menu
     */
    public static class Criteria extends GeneratedCriteria {


        protected Criteria() {
            super();
        }
    }

    /**
     * 订单中菜品信息
     * Criterion
     * 数据库表：order_menu
     */
    public static class Criterion {

        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}