package com.zdb.demo.entity;

import java.io.Serializable;

/**
 * 购物车
 * ShoppingCart
 * 数据库表：shopping_cart
 */
public class ShoppingCart implements Serializable {

    /**
     * 购物车主键id
     * 表字段 : shopping_cart.shopping_cart_id
     */
    private Integer shoppingCartId;

    /**
     * 用户id
     * 表字段 : shopping_cart.user_id
     */
    private Integer userId;

    /**
     * 菜品id
     * 表字段 : shopping_cart.menu_id
     */
    private Integer menuId;

    /**
     * 菜品数量
     * 表字段 : shopping_cart.menu_num
     */
    private Integer menuNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shopping_cart
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 购物车主键id 字段:shopping_cart.shopping_cart_id
     *
     * @return shopping_cart.shopping_cart_id, 购物车主键id
     */
    public Integer getShoppingCartId() {
        return shoppingCartId;
    }

    /**
     * 设置 购物车主键id 字段:shopping_cart.shopping_cart_id
     *
     * @param shoppingCartId the value for shopping_cart.shopping_cart_id, 购物车主键id
     */
    public void setShoppingCartId(Integer shoppingCartId) {
        this.shoppingCartId = shoppingCartId;
    }

    /**
     * 获取 用户id 字段:shopping_cart.user_id
     *
     * @return shopping_cart.user_id, 用户id
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * 设置 用户id 字段:shopping_cart.user_id
     *
     * @param userId the value for shopping_cart.user_id, 用户id
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * 获取 菜品id 字段:shopping_cart.menu_id
     *
     * @return shopping_cart.menu_id, 菜品id
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * 设置 菜品id 字段:shopping_cart.menu_id
     *
     * @param menuId the value for shopping_cart.menu_id, 菜品id
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * 获取 菜品数量 字段:shopping_cart.menu_num
     *
     * @return shopping_cart.menu_num, 菜品数量
     */
    public Integer getMenuNum() {
        return menuNum;
    }

    /**
     * 设置 菜品数量 字段:shopping_cart.menu_num
     *
     * @param menuNum the value for shopping_cart.menu_num, 菜品数量
     */
    public void setMenuNum(Integer menuNum) {
        this.menuNum = menuNum;
    }
}